### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by iliakan** [puntorigen/recover-source#1]
Prettier is undefined.

And then, if I fix it, on github copilot extension.js code:
```
➜  dist recover-source -i .
node:internal/fs/utils:916
    throw new ERR_INVALID_ARG_TYPE(
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
    at Object.writeFileSync (node:fs:2335:5)
    at /opt/local/lib/node_modules/recover-source/index.js:86:16
```

**Comment by abdu-70-m** [comment]
➜  dist recover-source -i .
node:internal/fs/utils:916
    throw new ERR_INVALID_ARG_TYPE(
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
    at Object.writeFileSync (node:fs:2335:5)
    at /opt/local/lib/node_modules/recover-source/index.js:86:16

**Comment by abdu-70-m** [comment]
➜  dist recover-source -i .
node:internal/fs/utils:916
    throw new ERR_INVALID_ARG_TYPE(
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
    at Object.writeFileSync (node:fs:2335:5)
    at /opt/local/lib/node_modules/recover-source/index.js:86:16

**Comment by abdu-70-m** [comment]
➜  dist recover-source -i .
node:internal/fs/utils:916
    throw new ERR_INVALID_ARG_TYPE(
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
    at Object.writeFileSync (node:fs:2335:5)
    at /opt/local/lib/node_modules/recover-source/index.js:86:16

**Comment by abdu-70-m** [comment]
![23FC1D7E-6F10-40D6-829D-1234D9AAF5E4](https://github.com/user-attachments/assets/7718b653-2a49-4a2c-910d-d02513e4d75b)
pwb

**Comment by abdu-70-m** [comment]
Uploading IMG_1320.MOV…

**Comment by abdu-70-m** [comment]
payshanba, 19-dekabr, 2024, 16:16

**Comment by abdu-70-m** [comment]
> payshanba, 19-dekabr, 2024, 16:16[pwd](url)

--mv

**Comment by abdu-70-m** [comment]
_Originally posted by @abdu-70-m in https://github.com/puntorigen/recover-source/issues/1#issuecomment-2558555564

**Comment by abdu-70-m** [comment]
> _Originally posted by @abdu-70-m in [#1 (comment)](https://github.com/puntorigen/recover-source/issues/1#issuecomment-2558555564)

**Comment by abdu-70-m** [comment]
[ali zokir](url)

**Comment by abdu-70-m** [comment]
[lo](url)_[AlistGo/alist](https://github.com/AlistGo/alist)
🗂️A file list/WebDAV program that supports multiple storages, powered by Gin and Solidjs. / 一个支持多存储的文件列表/WebDAV程序，使用 Gin 和 Solidjs。_

**Comment by abdu-70-m** [comment]
[lolo](url)_🔊 Oya & Bora - Sevme zamanı(speed up) `al aşkım beni yanına dalmışım sarhoşluğuna` [→](https://www.youtube.com/watch?v=NJWz8GXZBX0)

@xsosbot orqali istagan musiqangizni tez va oson toping!_
